service: edurain-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL, ''}
    RAZORPAY_KEY_ID: ${env:RAZORPAY_KEY_ID, ''}
    RAZORPAY_KEY_SECRET: ${env:RAZORPAY_KEY_SECRET, ''}
    NODE_ENV: production
    CORS_ORIGINS: ${env:CORS_ORIGINS, ''}
    PUBLIC_BASE_URL: ${env:PUBLIC_BASE_URL, ''}
    FIREBASE_SERVICE_ACCOUNT: ${env:FIREBASE_SERVICE_ACCOUNT, ''}
  vpc:
    securityGroupIds:
      - sg-0c07d868d37903d36
    subnetIds:
      - subnet-075e2e2d787f424a9
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: "arn:aws:s3:::edurain-media-v2/*"


package:
  patterns:
    - '!**'
    - 'dist/**'
    - '.env'
    - 'firebase-service-account.json'

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi: '*'
